web: python manage.py migrate --noinput; gunicorn untitled_football_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level info --access-logfile - --error-logfile -
worker: celery -A untitled_football_project worker -l info
beat: celery -A untitled_football_project beat -l info
