# Generated by Django 4.2.23 on 2026-02-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_game_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="stage",
            field=models.CharField(
                choices=[
                    ("PRE", "Pre Season"),
                    ("REG", "Regular Season"),
                    ("POST", "Post Season"),
                ],
                default="REG",
                max_length=20,
            ),
        ),
    ]
