# Generated by Django 4.2.23 on 2026-02-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_delete_team_players"),
        ("games", "0007_alter_game_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_games",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_games",
                to="teams.team",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["season", "week"], name="games_game_season_e4a392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["date"], name="games_game_date_b7173e_idx"),
        ),
    ]
