# Generated by Django 4.2.23 on 2026-02-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_delete_team_players"),
        ("games", "0008_audit_fixes"),
        ("players", "0007_player_season"),
        ("stats", "0008_add_advanced_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footballplayergamestat",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="footballplayergamestat",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_stats",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="footballteamgamestat",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_stats",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="footballteamgamestat",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_stats",
                to="teams.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="footballplayergamestat",
            unique_together={("player", "game")},
        ),
        migrations.AlterUniqueTogether(
            name="footballteamgamestat",
            unique_together={("team", "game")},
        ),
    ]
